const { GoogleGenAI } = require('@google/genai');
const puppeteer = require('puppeteer')

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const generateInterviewReport = async (resume, jobDescription, selfDescription) => {
  try {
    const prompt = `
You are an elite technical interviewer, a seasoned career coach, and a technical hiring manager at a top-tier tech company.
I am providing you with a candidate's resume, the job description for the role they are targeting, and their self-description.

Resume:
${resume || "Not provided"}

Job Description:
${jobDescription || "Not provided"}

Self Description:
${selfDescription || "Not provided"}

Your critical objective is to conduct a highly rigorous, deep-dive analysis of the alignment between the candidate's profile and the job requirements. Then, generate an intensive, highly detailed, and actionable interview preparation report.

Follow these strict guidelines for your analysis to ensure maximum detail and high-quality outputs:
1. **Match Score**: Provide a realistic, highly objective score measuring exact alignment in skills, experience, and domain knowledge.
2. **Technical Questions**: Generate advanced, scenario-based, and highly practical technical questions. Avoid generic questions. Focus on the intersection of the candidate's stated experience and the core demands of the job description. The "answer" should be deeply technical, including necessary concepts, trade-offs, and best practices.
3. **Behavioral Questions**: Construct complex situational behavioral questions (e.g., using the STAR method). Tailor them to the seniority level implied by the resume and the cultural/leadership traits suggested by the target role.
4. **Skill Gaps**: Identify critical missing skills or areas where the candidate falls short of the job description. Be hyper-specific.
5. **Preparation Plans**: Create a rigorous day-by-day action plan. Each daily focus should be highly specific (e.g., "Deep dive into React Server Components" rather than "Study React"). The tasks must be actionable, covering theoretical reading, practical coding exercises, and mock interview practice.

You MUST return the output as a valid JSON object following the EXACT structure below. Do not use markdown blocks or include any extra text outside the JSON.

REQUIRED JSON STRUCTURE:
{
  "matchScore": <integer representing a strict and accurate match score out of 100>,
  "technicalQuestions": [
    {
      "question": "<string: detailed, advanced, scenario-based question>",
      "intention": "<string: deep explanation of why this question perfectly validates the candidate's fit>",
      "answer": "<string: a highly comprehensive, expert-level ideal answer covering concepts and nuance>"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "<string: nuanced, situational behavioral question>",
      "intention": "<string: explicit target soft-skill or leadership principle being assessed>",
      "answer": "<string: a sophisticated ideal response leveraging the STAR framework>"
    }
  ],
  "skillGaps": [
    {
      "skill": "<string: highly specific technology, tool, or domain knowledge gap>",
      "severity": "<must be exactly one of: 'low', 'medium', 'high'>"
    }
  ],
  "preparationPlans": [
    {
      "day": <integer representing the day number, e.g., 1>,
      "focus": "<string: a highly specific and targeted theme for the day's study>",
      "tasks": [
        "<string: an actionable, rigorous study or practice task>",
        "<string: another highly detailed task>"
      ]
    }
  ]
}
`;

    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
      }
    });

    // The response will be exactly the JSON string due to responseMimeType
    if (response.text) {
      const reportData = JSON.parse(response.text);
      return reportData;
    } else {
      throw new Error("No response text generated by Gemini.");
    }

  } catch (error) {
    console.error("Error generating interview report using Gemini:", error);
    throw error;
  }
};

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  })
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: "networkidle0" })

  const pdfBuffer = await page.pdf({
    format: "A4", margin: {
      top: "20mm",
      bottom: "20mm",
      left: "15mm",
      right: "15mm"
    }
  })

  await browser.close()

  return pdfBuffer
};

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  try {
    const resumePdfSchema = {
      type: "object",
      properties: {
        html: {
          type: "string",
          description: "The HTML content of the resume which can be converted to PDF using any library like puppeteer"
        }
      },
      required: ["html"]
    };

    const prompt = `You are an expert resume writer and ATS-optimization specialist. Your task is to generate a highly professional, optimized resume in pure HTML format for a candidate. 
    
    Here are the source materials:
    --- ORIGINAL RESUME ---
    ${resume || "Not provided"}
    
    --- CANDIDATE SELF DESCRIPTION ---
    ${selfDescription || "Not provided"}
    
    --- TARGET JOB DESCRIPTION ---
    ${jobDescription || "Not provided"}
    
    CRITICAL INSTRUCTIONS:
    1. STRICT DATA RETENTION: You MUST explicitly retain all personal contact information and essential links from the Original Resume and Self Description. NEVER drop, alter, or omit any GitHub links, LinkedIn URLs, portfolio websites, email addresses, or phone numbers.
    2. THOROUGH INTEGRATION: Carefully merge the facts, projects, and achievements from the Original Resume and Self Description. Enhance and tailor the descriptions to perfectly align with the core requirements and keywords of the Target Job Description without fabricating false experience.
    3. ATS-FRIENDLY HTML: The output must strictly be a well-structured, single-file HTML document (with internal CSS). Use standard semantic HTML5 tags (e.g., <header>, <section>, <h1>, <ul>) to ensure ATS compatibility. 
    4. PROFESSIONAL DESIGN & AESTHETICS: Embed minimal, modern CSS styles in the <head>. The layout should be visually striking yet highly professional, using clean typography (e.g., standard sans-serif font stacks), appropriate margins, and subtle highlights for headers/roles.
    5. QUALITY OVER QUANTITY: Ensure the resume is impactful, concise, and reads identically to a premium human-written resume. Quantify achievements where possible. It must render perfectly into 1-2 pages when converted to PDF via Puppeteer.

    OUTPUT FORMAT:
    The response must be a JSON object containing EXACTLY ONE field:
    {
      "html": "<string: the complete, fully styled HTML document for the resume>"
    }
    `;

    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: resumePdfSchema,
      }
    })


    const jsonContent = JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer
  } catch (error) {
    console.error("Error generating resume pdf using Gemini:", error);
    throw error;
  }

};

module.exports = {
  generateInterviewReport,
  generatePdfFromHtml,
  generateResumePdf
};
